### ISSUE TITLE
Tracker#set method no longer receives the expected response.

### ISSUE THREAD

**Issue by dlikhten** [zevarito/mixpanel#123]
Looks like mixpanel may have changed their API. The #set no longer works.

Site note: They now have this nifty https://github.com/mixpanel/mixpanel-ruby gem which just handles the ruby side of transmission, but doesn't do client side middleware, or the async: true feature.

Sounds like we basically should wrap all ruby-side calls with invocations of the original gem.

```
NoMethodError: undefined method `body' for 1:Fixnum
from /Users/dlikhten/.rvm/gems/ruby-2.0.0-p247@global/gems/mixpanel-4.0.7/lib/mixpanel/tracker.rb:71:in `parse_response'
```

**Comment by reconbot** [comment]
It doesn't appear they have changed their api, is this ongoing?

The mixpanel blessed gem does look interesting, however it's premature to change over to it.

**Comment by dlikhten** [comment]
This happened today. I'll investigate more tomorrow.

**Comment by dlikhten** [comment]
I just made a manual request to mixpanel's api with the data, the response is not a JSON, but rather an integer.

**Comment by xxx** [comment]
+1. We have the exact same issue since upgrade to 4.0.7 from 4.0.5 yesterday.

**Comment by reconbot** [comment]
Downgrading to `4.0.5` will solve this issue for now.

**Comment by dlikhten** [comment]
The offending commit: https://github.com/zevarito/mixpanel/commit/3e1cb1c863ec513695c0e46007f5641f535e4fe1
